/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 *
 * @author ariel
 */
public class VentanaRegistroDeEntrada extends javax.swing.JInternalFrame {

    private VentanaCrearVehiculo ventanaCrearVehiculo;
    private VentanaCrearCliente ventanaCrearCliente;
    /**
     * Creates new form VentanaRegistroDeEntrada
     */
    public VentanaRegistroDeEntrada() {
        initComponents();
        
        //Ventanas
        this.ventanaCrearCliente = new VentanaCrearCliente();
        this.ventanaCrearVehiculo = new VentanaCrearVehiculo(this, ventanaCrearCliente);
        
        //agrego las ventanas internas
        jDesktopPane1.add(ventanaCrearCliente);
        jDesktopPane1.add(ventanaCrearVehiculo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelPrincipal1 = new javax.swing.JPanel();
        jLabelNumeroDeTicket1 = new javax.swing.JLabel();
        jTextFieldNumeroDeTicket1 = new javax.swing.JTextField();
        jTextFieldFechaDeIngreso1 = new javax.swing.JTextField();
        jLabelFechaDeIngreso1 = new javax.swing.JLabel();
        jScrollPaneTablaVehiculos1 = new javax.swing.JScrollPane();
        jTableVehiculos1 = new javax.swing.JTable();
        jLabelPlaca1 = new javax.swing.JLabel();
        jTextFieldPlaca1 = new javax.swing.JTextField();
        jLabelTitulo1 = new javax.swing.JLabel();
        jPanelDatosCliente1 = new javax.swing.JPanel();
        jLabelCedula1 = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelDireccion1 = new javax.swing.JLabel();
        jLabelTelefono1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jTextFieldTelefono1 = new javax.swing.JTextField();
        jTextFieldDireccion1 = new javax.swing.JTextField();
        jTextFieldCedula1 = new javax.swing.JTextField();
        jButtonRegistrarTicket = new javax.swing.JButton();
        jButtonCrearVehiculo = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanelPrincipal1.setBackground(new java.awt.Color(12, 131, 131));
        jPanelPrincipal1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNumeroDeTicket1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelNumeroDeTicket1.setText("Numero de Ticket :");

        jTextFieldNumeroDeTicket1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldFechaDeIngreso1.setEditable(false);
        jTextFieldFechaDeIngreso1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelFechaDeIngreso1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelFechaDeIngreso1.setText("Fecha y Hora de Ingreso:");

        jTableVehiculos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTablaVehiculos1.setViewportView(jTableVehiculos1);

        jLabelPlaca1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelPlaca1.setText("Placa del vehiculo:");

        jTextFieldPlaca1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelTitulo1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabelTitulo1.setText("Registrar Entrada");

        jPanelDatosCliente1.setBackground(new java.awt.Color(12, 131, 131));
        jPanelDatosCliente1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos del cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Narrow", 0, 22))); // NOI18N

        jLabelCedula1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelCedula1.setText("Cedula:");

        jLabelNombre1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelNombre1.setText("Nombre:");

        jLabelDireccion1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelDireccion1.setText("Direccion:");

        jLabelTelefono1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabelTelefono1.setText("Telefono:");

        jTextFieldNombre1.setEditable(false);
        jTextFieldNombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldTelefono1.setEditable(false);
        jTextFieldTelefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldDireccion1.setEditable(false);
        jTextFieldDireccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldCedula1.setEditable(false);
        jTextFieldCedula1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelDatosCliente1Layout = new javax.swing.GroupLayout(jPanelDatosCliente1);
        jPanelDatosCliente1.setLayout(jPanelDatosCliente1Layout);
        jPanelDatosCliente1Layout.setHorizontalGroup(
            jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosCliente1Layout.createSequentialGroup()
                        .addComponent(jLabelTelefono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosCliente1Layout.createSequentialGroup()
                        .addComponent(jLabelCedula1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosCliente1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosCliente1Layout.createSequentialGroup()
                        .addComponent(jLabelDireccion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDatosCliente1Layout.setVerticalGroup(
            jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosCliente1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula1)
                    .addComponent(jTextFieldCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre1)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion1)
                    .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono1)
                    .addComponent(jTextFieldTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jButtonRegistrarTicket.setText("Registrar ticket");

        jButtonCrearVehiculo.setText("Crear nuevo vehiculo");
        jButtonCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipal1Layout = new javax.swing.GroupLayout(jPanelPrincipal1);
        jPanelPrincipal1.setLayout(jPanelPrincipal1Layout);
        jPanelPrincipal1Layout.setHorizontalGroup(
            jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTablaVehiculos1)
                .addContainerGap())
            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipal1Layout.createSequentialGroup()
                        .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                                .addComponent(jLabelNumeroDeTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumeroDeTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                                .addComponent(jButtonRegistrarTicket)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonCrearVehiculo))
                            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                                .addComponent(jLabelPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                                .addComponent(jLabelFechaDeIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldFechaDeIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipal1Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo1)
                        .addGap(53, 53, 53)))
                .addComponent(jPanelDatosCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelPrincipal1Layout.setVerticalGroup(
            jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroDeTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumeroDeTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechaDeIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaDeIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCrearVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jButtonRegistrarTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelPrincipal1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanelDatosCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTablaVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanelPrincipal1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearVehiculoActionPerformed
        ventanaCrearVehiculo.setVisible(true);
    }//GEN-LAST:event_jButtonCrearVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearVehiculo;
    private javax.swing.JButton jButtonRegistrarTicket;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelCedula1;
    private javax.swing.JLabel jLabelDireccion1;
    private javax.swing.JLabel jLabelFechaDeIngreso1;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNumeroDeTicket1;
    private javax.swing.JLabel jLabelPlaca1;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanelDatosCliente1;
    private javax.swing.JPanel jPanelPrincipal1;
    private javax.swing.JScrollPane jScrollPaneTablaVehiculos1;
    private javax.swing.JTable jTableVehiculos1;
    private javax.swing.JTextField jTextFieldCedula1;
    private javax.swing.JTextField jTextFieldDireccion1;
    private javax.swing.JTextField jTextFieldFechaDeIngreso1;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNumeroDeTicket1;
    private javax.swing.JTextField jTextFieldPlaca1;
    private javax.swing.JTextField jTextFieldTelefono1;
    // End of variables declaration//GEN-END:variables
}
