/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author ariel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Locale localizacion;
    private ResourceBundle mensajes;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        localizacion = new Locale("es","EC");
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idioma.mensajes", localizacion);
        cambiarIdioma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistroEntrada = new javax.swing.JButton();
        btnRegistroSalida = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemIniciarSecion = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jMenuRegistros = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenuItemTickets = new javax.swing.JMenuItem();
        jMenuIdioma = new javax.swing.JMenu();
        jMenuItemEspañol = new javax.swing.JMenuItem();
        jMenuItemIngles = new javax.swing.JMenuItem();
        jMenuAjustes = new javax.swing.JMenu();
        jMenuItemCambiarColor = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parqueadero UPS");
        setPreferredSize(new java.awt.Dimension(808, 700));
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(48, 102, 109));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel1.setText("Parqueadero UPS");

        btnRegistroEntrada.setText("Registro de Entrada");

        btnRegistroSalida.setText("Registro de Salida");

        jButton4.setText("jButton4");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/imagenMenu2.PNG.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistroSalida)
                    .addComponent(btnRegistroEntrada)
                    .addComponent(jButton4))
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnRegistroEntrada)
                        .addGap(72, 72, 72)
                        .addComponent(btnRegistroSalida)
                        .addGap(93, 93, 93)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setForeground(new java.awt.Color(0, 102, 102));

        jMenuInicio.setText("Inicio");
        jMenuInicio.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N

        jMenuItemIniciarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/iniciar-sesion.png"))); // NOI18N
        jMenuItemIniciarSecion.setText("Iniciar Sesion");
        jMenuInicio.add(jMenuItemIniciarSecion);

        jMenuItemCerrar.setText("Cerrar");
        jMenuInicio.add(jMenuItemCerrar);

        menuBar.add(jMenuInicio);

        jMenuRegistros.setMnemonic('f');
        jMenuRegistros.setText("Registros");
        jMenuRegistros.setFocusTraversalPolicyProvider(true);
        jMenuRegistros.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N

        jMenuItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/hotel (1).png"))); // NOI18N
        jMenuItemClientes.setMnemonic('o');
        jMenuItemClientes.setText("Clientes");
        jMenuRegistros.add(jMenuItemClientes);

        jMenuItemVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/registro.png"))); // NOI18N
        jMenuItemVehiculos.setMnemonic('s');
        jMenuItemVehiculos.setText("Vehiculos");
        jMenuRegistros.add(jMenuItemVehiculos);

        jMenuItemTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/boleto-de-validacion.png"))); // NOI18N
        jMenuItemTickets.setMnemonic('a');
        jMenuItemTickets.setText("Tickets");
        jMenuRegistros.add(jMenuItemTickets);

        menuBar.add(jMenuRegistros);

        jMenuIdioma.setMnemonic('e');
        jMenuIdioma.setText("Idioma");
        jMenuIdioma.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N

        jMenuItemEspañol.setMnemonic('t');
        jMenuItemEspañol.setText("Español");
        jMenuIdioma.add(jMenuItemEspañol);

        jMenuItemIngles.setMnemonic('y');
        jMenuItemIngles.setText("Ingles");
        jMenuIdioma.add(jMenuItemIngles);

        menuBar.add(jMenuIdioma);

        jMenuAjustes.setText("Ajustes");
        jMenuAjustes.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N

        jMenuItemCambiarColor.setText("Cambiar color del Fondo");
        jMenuItemCambiarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarColorActionPerformed(evt);
            }
        });
        jMenuAjustes.add(jMenuItemCambiarColor);

        menuBar.add(jMenuAjustes);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCambiarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCambiarColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void cambiarIdioma() {
        System.out.println("Cambio de idioma ejecutado correctamente");
        jMenuAjustes.setText(mensajes.getString("ajustes"));
        jMenuIdioma.setText(mensajes.getString("idioma"));
        jMenuInicio.setText(mensajes.getString("inicio"));
        jMenuItemCambiarColor.setText(mensajes.getString("cambiarColorDelFondo"));
        jMenuItemCerrar.setText(mensajes.getString("cerrar"));
        jMenuItemClientes.setText(mensajes.getString("clientes"));
        jMenuItemEspañol.setText(mensajes.getString("español"));
        jMenuItemIngles.setText(mensajes.getString("ingles"));
        jMenuItemIniciarSecion.setText(mensajes.getString("iniciarSesion"));
        jMenuItemTickets.setText(mensajes.getString("tickets"));
        jMenuItemVehiculos.setText("vehiculos");
        jMenuRegistros.setText(mensajes.getString("registros"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroEntrada;
    private javax.swing.JButton btnRegistroSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAjustes;
    private javax.swing.JMenu jMenuIdioma;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemCambiarColor;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEspañol;
    private javax.swing.JMenuItem jMenuItemIngles;
    private javax.swing.JMenuItem jMenuItemIniciarSecion;
    private javax.swing.JMenuItem jMenuItemTickets;
    private javax.swing.JMenuItem jMenuItemVehiculos;
    private javax.swing.JMenu jMenuRegistros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
